---
    # # démarrage du service
    # - name: start docker service
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes
- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes